# Generated by Django 2.2.6 on 2020-04-03 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='csv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='varapp.Csv'),
        ),
    ]
