# Generated by Django 2.2.6 on 2020-04-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varapp', '0002_auto_20200403_1217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Journal',
        ),
    ]
