# Generated by Django 2.2.6 on 2020-04-03 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('varapp', '0003_auto_20200403_1220'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Journal',
        ),
    ]
