# Generated by Django 2.2.6 on 2020-04-03 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('varapp', '0004_delete_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npa_key', models.CharField(blank=None, default=None, max_length=100, null=True)),
                ('npa_val', models.CharField(blank=None, default=None, max_length=100, null=True)),
                ('csv', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='varapp.Csv')),
            ],
        ),
    ]
